# Generated by Django 4.0.3 on 2022-03-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(default='', max_length=2083),
        ),
    ]
